### ISSUE TITLE
[Feature Request] What about sending custom data along with the key

### ISSUE THREAD

**Issue by nagi1** [laravel-ready/license-connector#1]
Hey,

Thank you, for this awesome work!

I'm working on a product where I need to send custom data i.e Client application user count, version and some other data. user count along with the license key. 

Thinking about contributing this little feature. what do you think?

**Comment by relliv** [comment]
Hi,

What is the user count and how will it work? Could you give an example?

**Comment by relliv** [comment]
And how do we catch this data on the server package side?

**Comment by nagi1** [comment]
Ability to send custom data with `post` in https://github.com/laravel-ready/license-connector/blob/5af50ddbb4637bb7074678a863122130bb5405ce/src/Services/ConnectorService.php#L41,L43

and use this data in the license server to help validate with the key

**Comment by relliv** [comment]
In this case, there is three-way to handle custom data. Custom Controller, Event Listener, and Custom Middleware option. Each case has its own advantages and disadvantages.

- [x] **Middleware**: you can handle custom data while request processing.
- [x] **Event Listener**: you can get license validation results etc. and custom data.
- [x] **Controller**: you have to write your own validation but you can handle custom data and you can manipulate the response.

**Comment by relliv** [comment]
I think this issue solved. If you want to continue to discuss you are free to reopen.
